### PR TITLE
fix: useIsComponentMounted is incompatible with React StrictMode

### LINKED ISSUE #12: useIsComponentMounted is incompatible with React StrictMode (React 18+)
### Summary

`useIsComponentMounted` initializes `useRef(true)` and only sets `ref.current = false` in the effect cleanup, without restoring it to `true` in the effect body. This causes the hook to permanently report `false` after React StrictMode's double-invocation cycle in React 18+.

The current implementation:

```ts
// useIsComponentMounted.ts (current)
const isComponentMountedRef = useRef(true);

useEffect(() => {
  return () => {
    isComponentMountedRef.current = false;
  };
}, []);
```

### Expected behavior

After a component mounts (including StrictMode's `mount → unmount → mount` cycle), `useIsComponentMounted()` should return `true`. Async callbacks gated by `isMounted()` should execute normally and update state.

### Actual behavior

In React 18+ with StrictMode enabled, React intentionally double-invokes effects for newly mounted components (`mount → unmount → mount`) to ensure compatibility with reusable state ([reactwg/react-18#19](https://github.com/reactwg/react-18/discussions/19)).

During this cycle:

1. **First mount** — effect runs, cleanup is registered. `ref.current` stays `true` (initial value).
2. **Unmount (cleanup)** — cleanup sets `ref.current = false`.
3. **Second mount** — effect re-runs, but the body has no code to restore `ref.current` back to `true`.

After step 3, `isComponentMountedRef.current` is permanently `false`. Any async callback checking `isMounted()` sees `false` and skips state updates, leaving the UI stuck (e.g., infinite loading spinners).

### Reproduction

1. Wrap any component using `useIsComponentMounted` with `<React.StrictMode>`.
2. Inside the component, fetch data asynchronously and guard `setState` with `isMounted()`.
3. Observe that `isMounted()` returns `false` after mount, and state is never updated.

### Package version number

1.2.1

### Browser

any

### Device

any

### PR DESCRIPTION
**Pull request by Winterfulllll**
Closes [this issue](https://github.com/kommo-crm/react-hooks/issues/12)

### CODE REVIEW

File: src/useIsComponentMounted/useIsComponentMounted.ts [hunk 1]
```diff
@@ -1,9 +1,11 @@
 import { useRef, useEffect } from 'react';
 
 export const useIsComponentMounted = (): (() => boolean) => {
-  const isComponentMountedRef = useRef(true);
+  const isComponentMountedRef = useRef(false);
 
   useEffect(() => {
+    isComponentMountedRef.current = true;
```
Comment (igoryusha22) [inline src/useIsComponentMounted/useIsComponentMounted.ts:23]: Should we add it above?

const isComponentMountedRef = useRef(true);
isComponentMountedRef.current = true;

So its true at first render?

Comment (Winterfulllll) [reply src/useIsComponentMounted/useIsComponentMounted.ts:23]: I'd recommend against that. Two reasons:

1. Mutating a ref during render is a side effect. React discourages side effects during render - in concurrent mode, renders can be interrupted and replayed, so writing to `ref.current` in the component body is not safe.
2. It's unnecessary in practice. This hook is designed for async callbacks (after `fetch`, `setTimeout`, etc.) that resolve after effects have already run. By that time, the effect has already set ref.current = true. You'd never need to call `isMounted()` synchronously during render - the component is obviously mounted if it's rendering.

So the current fix is the correct idiomatic pattern.

**Comment by igoryusha22** [comment]
lgtm.
